### ISSUE TITLE
Environment configuration errors...

### ISSUE THREAD

**Issue by Ian-YJX** [nerfdeformer/nerfdeformer#1]
When I tried to install the virtual environment with 
`conda install --file src/correspondence_matching/environment.yaml`,
 there's a 
`CondaValueError: could not parse 'name: matching' in: src/correspondence_matching/environment.yaml`. 
And I tried to input 
`conda env create -f src/correspondence_matching/environment.yaml`, 
there's also something wrong(shown in the enclosed picture).  My device is Ubuntu 24.04, is there any way to solve my problem? thanks.
![截图 2024-06-27 15-54-33](https://github.com/nerfdeformer/nerfdeformer/assets/125331132/a9596376-c453-4964-a8fd-1362b3dfe1e1)

**Comment by recordmp3** [comment]
Updated a new environment.yaml. please run `conda create env -f src/correspondence_matching/environment.yaml && conda activate matching && pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113` again.
